### ISSUE TITLE
[Task] 비밀번호 확인 기능 구현

### ISSUE THREAD

**Issue by alskfl222** [codestates/book-log#18]
### **ISSUE**

- Group: `server`
- Type: `feature`
- Detail: check password

### **TODO**

- [x] request 토큰 확인
- [x] 토큰 내 사용자 정보 조건으로 db 검색
- [x] 비밀번호가 일치하는지 확인 
- [x] 결과 response 전송

### **Labels**

- Estimated time: `E: 1h`
- Group : `server`
- Sprint: `Sprint 2`
- Urgency: `High`
