### ISSUE TITLE
[Task] 비밀번호 변경 기능 구현

### ISSUE THREAD

**Issue by alskfl222** [codestates/book-log#21]
### **ISSUE**

- Group: `server`
- Type: `feature`
- Detail: modify password

### **TODO**

- [x] request 토큰 확인
- [ ] 토큰 내 사용자 정보 조건으로 db 검색
- [ ] db 내 비밀번호를 업데이트 시도
- [ ] 결과 response 전송

### **Labels**

- Estimated time: `E: 1.5h`
- Group : `server`
- Sprint: `Sprint 2`
- Urgency: `High`
