### ISSUE TITLE
[Task] 회원탈퇴 기능 구현

### ISSUE THREAD

**Issue by alskfl222** [codestates/book-log#25]
### **ISSUE**

- Group: `server`
- Type: `feature`
- Detail: delete user in database

### **TODO**

- [ ] request 토큰 확인
- [ ] 토큰 내 사용자 정보 조건으로 db 검색
- [ ] db와 request 본문의 비밀번호 일치 여부 확인
- [ ] 일치하다면 db 내용 삭제 후 결과 전송

### **Labels**

- Estimated time: `E: 1h`
- Group : `server`
- Sprint: `Sprint 2`
- Urgency: `High`
