### ISSUE TITLE
[Task] 책 목록 조회 기능

### ISSUE THREAD

**Issue by alskfl222** [codestates/book-log#3]
### **ISSUE**

- Group: `server`
- Type: `feature`
- Detail: read book list

### **TODO**

- [x] request 토큰 확인
- [x] database 조회 후 결과 받기 (사용자 필터)
- [x] 조회 결과를 response로 전송

### **Labels**

- Estimated time: `E: 2h`
- Group : `Bare-minimum`, `Server`
- Sprint: `Sprint 2`
- Urgency: `High`
