### ISSUE TITLE
[Task] 프로토타입 작성

### ISSUE THREAD

**Issue by kimdoyeonn** [codestates/book-log#41]
### **ISSUE**

- Group: `sr`
- Type: `feature`,
- Detail: Book Log 프로토타입 작성

### **TODO**

- [x]  회원 관련 페이지
- [x]  조회 관련 페이지(도서 조회, 감상 조회)
- [x]  작성 관련 페이지(감상 작성, 수정)

### **Estimated time**

> Pick one
> 

### **Labels**

- Estimated time: `E: 2.5h`
- Group : `client`, `server`
- Sprint: `Sprint 1`
- Urgency: `High`
