### ISSUE TITLE
[Task] 회원가입 페이지

### ISSUE THREAD

**Issue by boraborayoon** [codestates/book-log#5]
### **ISSUE**

- Group: `client`
- Type: `feature`
- Detail: 회원가입 페이지 구현 및 유효성 검사

### **TODO**

- [x]  이메일 중복체크
- [x]  이메일 유효성 검사
- [x]  비밀번호 유효성 검사(두번 입력한게 동일한지, 길이가 8자인지)
- [x] axios로 회원가입 요청

### **Labels**

- Estimated time: `E: 2h`
- Group : `client`
- Sprint: `Sprint 2`
- Urgency: `High`
