### ISSUE TITLE
[Task] 주기적으로 메일 전달하기

### ISSUE THREAD

**Issue by kimdoyeonn** [codestates/book-log#84]
### **ISSUE**

- Group: `server`
- Type: `feature`
- Detail: 한 달에 한 번 전 달에 작성한 감상을 회원의 이메일로 전송하기

### **TODO**

- [x]  매월 1일 8시에 전송
- [x]  회원이 작성한 모든 감상을 조회
- [x]  조회된 데이터를 보내기 쉽도록 객체로 만듦

### **Estimated time**

> Pick one
> 

### **Labels**

- Estimated time: `E: 1h`
- Group :  `server`
- Sprint: `Sprint 3`
- Urgency: `Middle`
